#!/usr/bin/env python3
"""CI guard: is frontend/data.js in sync with data/systems/*.json?

`frontend/data.js` is GENERATED by `backend-data/build.py`. It must never be
hand-edited, and every edit to a `data/systems/*.json` record must be followed
by a rebuild. This check enforces that: it re-runs `build.py` against the
current data tree and compares the regenerated `data.js` to the committed one.

What is compared: the `systems` array and the five *data-derived* stats
(systems, with_coords, image_records, with_local_image, planet_hosts).

What is deliberately ignored:
  * `generated`  — a wall-clock timestamp that changes every build.
  * `papers_known` / `papers_explored` / `papers_in_atlas` — these depend on
    `data/paper_finder/candidates.json`, which is gitignored and therefore
    absent in a fresh CI checkout. They are not part of the record contract.

The check is side-effect-free: it restores the pre-existing `data.js` before
exiting, so it is safe to run against a dirty working tree.

Exit 0 = in sync; exit 1 = drift (rebuild needed) or `build.py` failed.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_JS = ROOT / "frontend" / "data.js"
BUILD = ROOT / "backend-data" / "build.py"

# stats that derive purely from data/systems/*.json (tracked, reproducible)
DETERMINISTIC_STATS = (
    "systems", "with_coords", "image_records", "with_local_image", "planet_hosts",
)


def parse(text):
    """Parse `window.ATLAS = {...};` into a dict."""
    start = text.index("{")
    end = text.rindex("}") + 1
    return json.loads(text[start:end])


def comparable(payload):
    stats = payload.get("stats", {})
    return {
        "systems": payload.get("systems"),
        "stats": {k: stats.get(k) for k in DETERMINISTIC_STATS},
    }


def main():
    if not DATA_JS.exists():
        print("ERROR: frontend/data.js is missing", file=sys.stderr)
        return 1

    committed = DATA_JS.read_text(encoding="utf-8")
    try:
        proc = subprocess.run(
            [sys.executable, str(BUILD)],
            cwd=str(ROOT), capture_output=True, text=True,
        )
        rebuilt = DATA_JS.read_text(encoding="utf-8")
    finally:
        # always restore the committed file — never leave a side effect
        DATA_JS.write_text(committed, encoding="utf-8")

    if proc.returncode != 0:
        print("ERROR: backend-data/build.py failed:\n" + proc.stderr, file=sys.stderr)
        return 1

    want = comparable(parse(committed))
    got = comparable(parse(rebuilt))

    if want == got:
        n = len(want["systems"] or [])
        print(f"OK: frontend/data.js is in sync ({n} systems).")
        return 0

    print("ERROR: frontend/data.js is OUT OF SYNC with data/systems/*.json.",
          file=sys.stderr)
    print("       Run:  python3 backend-data/build.py   and commit the result.",
          file=sys.stderr)

    # deterministic stats diff
    for k in DETERMINISTIC_STATS:
        a, b = want["stats"][k], got["stats"][k]
        if a != b:
            print(f"  stats.{k}: committed={a} rebuilt={b}", file=sys.stderr)

    # which systems changed (by id), capped for readability
    by_id_a = {s.get("id"): s for s in (want["systems"] or [])}
    by_id_b = {s.get("id"): s for s in (got["systems"] or [])}
    changed = sorted(
        i for i in set(by_id_a) | set(by_id_b)
        if by_id_a.get(i) != by_id_b.get(i)
    )
    if changed:
        shown = ", ".join(changed[:15])
        more = f" (+{len(changed) - 15} more)" if len(changed) > 15 else ""
        print(f"  changed systems: {shown}{more}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
