#!/usr/bin/env python3
"""Coverage audit: which observing modalities does each system have images for?

Modalities: mm (ALMA/SMA/interferometry), nir (scattered light 0.9-2.5 um),
opt (scattered light <0.9 um), tir (thermal IR >3 um imaging), planet (companion image).

Writes data/coverage_todo.md: for every system, the missing modalities plus
ready-made search queries ("<name> ALMA arXiv", "<name> SPHERE polarimetric", ...).
Agents work top-down through this file; systems with fewer records rank first.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYS = ROOT / "data" / "systems"
OUT = ROOT / "data" / "coverage_todo.md"

QUERIES = {
    "mm": "{n} ALMA continuum disk arXiv",
    "nir": "{n} SPHERE OR GPI polarimetric scattered light arXiv",
    "opt": "{n} HST STIS OR ACS coronagraphy disk arXiv",
    "tir": "{n} JWST OR MIRI OR mid-infrared imaging disk arXiv",
}


def modality(im):
    wl = im.get("wavelength_um") or 0
    t = im.get("type")
    if t == "planet":
        return "planet"
    if t == "disk_mm" and wl > 100:
        return "mm"
    if wl >= 3:
        return "tir"
    if wl >= 0.9:
        return "nir"
    return "opt"


def main():
    rows = []
    for f in sorted(SYS.glob("*.json")):
        s = json.loads(f.read_text())
        have = {modality(im) for im in s.get("images", []) if im.get("file")}
        pend = {modality(im) for im in s.get("images", []) if not im.get("file")}
        if "quasar" in (s.get("categories") or []):
            want = set()                          # quasar hosts: no disk-modality baseline
        else:
            want = {"mm", "nir"}                  # baseline for every disk system
        if s.get("planets"):
            want.add("planet")
        missing = sorted(want - have - pend)
        rows.append((len(have), s["name"], s["id"], sorted(have), sorted(pend), missing))

    rows.sort(key=lambda r: (r[0], r[1]))
    lines = ["# Coverage audit (auto-generated by backend-data/coverage_audit.py)",
             "",
             "Systems sorted by how few image modalities they have. For each missing",
             "modality, run the suggested web search; if a published resolved image",
             "exists, add a pending record + arXiv id to the system JSON, regenerate",
             "fetch_sources.sh, host-fetch, crop. Mark '(none exists)' in the system's",
             "notes if the search comes up empty so future audits skip it.",
             ""]
    n_gap = 0
    for nh, name, sid, have, pend, missing in rows:
        if not missing:
            continue
        n_gap += 1
        lines.append(f"## {name} (`{sid}`) — has: {', '.join(have) or 'nothing local'}"
                     + (f"; pending: {', '.join(pend)}" if pend else ""))
        for m in missing:
            lines.append(f"- missing **{m}** → search: `{QUERIES.get(m, '{n} imaging arXiv').format(n=name)}`")
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"{n_gap} systems with gaps -> {OUT}")


if __name__ == "__main__":
    main()
